# version: "3"
# services:
#   db:
#     image: postgres:latest
#     environment:
#       # POSTGRES_USER: postgres
#       # POSTGRES_PASSWORD: postgres
#       # POSTGRES_DB: testdb
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=testdb
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     depends_on:
#       - db
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_NAME=testdb
#       - DB_USER=postgres
#       - DB_PASSWORD=postgres
#       # DB_HOST: db
#       # DB_PORT: 5432
#       # DB_USER: testdb
#       # DB_PASSWORD: postgres
#       # DB_NAME: postgres
#     ports:
#       - "8080:8080"

#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     depends_on:
#       - server
#     ports:
#       - "3000:3000"

# volumes:
#   db_data:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_NAME=testdb
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MONGO_URL=mongodb://mongo:27017/questionsdb

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
